# Generated by Django 5.2 on 2025-09-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
